sudo: required

services:
  - docker

env:
  global:
    - ALEPH_DATABASE_NAME=aleph
    - ALEPH_DATABASE_URI=postgresql://localhost/$ALEPH_DATABASE_NAME
    - DOCKER_COMPOSE_VERSION=1.16.1
    - DOCKER_IMAGE_NAME=alephdata/aleph

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo sysctl -w vm.max_map_count=262144
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo echo "ALEPH_DATABASE_NAME=$ALEPH_DATABASE_NAME\nALEPH_DATABASE_URI=$ALEPH_DATABASE_URI\nOAUTH_KEY=$OAUTH_KEY\nOAUTH_SECRET=$OAUTH_SECRET" >> aleph.env
  - docker --version
  - docker-compose --version
  - docker pull alephdata/aleph
  - docker pull alephdata/ui
  - docker pull alephdata/aleph-convert-document
  - docker pull alephdata/aleph-recognize-text
  - docker pull alephdata/aleph-extract-entities
  - docker pull alephdata/aleph-extract-countries

install:
  - echo "${TRAVIS_BRANCH}"
  - docker build --cache-from alephdata/aleph -t alephdata/aleph .
  - docker build --cache-from alephdata/ui -t alephdata/ui ui
  - docker build --cache-from alephdata/aleph-convert-document -t alephdata/aleph-convert-document services/convert-document
  - docker build --cache-from alephdata/aleph-recognize-text -t alephdata/aleph-recognize-text services/recognize-text
  - docker build --cache-from alephdata/aleph-extract-entities -t alephdata/aleph-extract-entities services/extract-entities
  - docker build --cache-from alephdata/aleph-extract-countries -t alephdata/aleph-extract-countries services/extract-countries
  - docker-compose -f docker-compose.dev.yml up -d postgres elasticsearch
  - sleep 4

script:
  - docker-compose -f docker-compose.dev.yml run --rm app /aleph/contrib/devwrapper.sh /aleph/contrib/test.sh

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # push tag as well
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      docker tag alephdata/aleph-convert-document alephdata/aleph-convert-document:$TRAVIS_TAG ;
      docker push alephdata/aleph-convert-document ;
      docker push alephdata/aleph-convert-document:$TRAVIS_TAG ;
      docker tag alephdata/aleph-recognize-text alephdata/aleph-recognize-text:$TRAVIS_TAG ;
      docker push alephdata/aleph-recognize-text ;
      docker push alephdata/aleph-recognize-text:$TRAVIS_TAG ;  
      docker tag alephdata/aleph-extract-entities alephdata/aleph-extract-entities:$TRAVIS_TAG ;
      docker push alephdata/aleph-extract-entities ;
      docker push alephdata/aleph-extract-entities:$TRAVIS_TAG ;
      docker tag alephdata/aleph-extract-countries alephdata/aleph-extract-countries:$TRAVIS_TAG ;
      docker push alephdata/aleph-extract-countries ;
      docker push alephdata/aleph-extract-countries:$TRAVIS_TAG ;
      docker tag alephdata/aleph alephdata/aleph:$TRAVIS_TAG ;
      docker push alephdata/aleph ;
      docker push alephdata/aleph:$TRAVIS_TAG ;
      docker tag alephdata/ui alephdata/ui:$TRAVIS_TAG ;
      docker push alephdata/ui ;
      docker push alephdata/ui:$TRAVIS_TAG ;
    fi
  - if [[ $TRAVIS_BRANCH = "occrp/production" ]]; then
      docker tag alephdata/aleph-convert-document alephdata/aleph-convert-document:occrp ;
      docker push alephdata/aleph-convert-document:occrp ;
      docker tag alephdata/aleph-recognize-text alephdata/aleph-recognize-text:occrp ;
      docker push alephdata/aleph-recognize-text:occrp ;
      docker tag alephdata/aleph-extract-entities alephdata/aleph-extract-entities:occrp ;
      docker push alephdata/aleph-extract-entities:occrp ;
      docker tag alephdata/aleph-extract-countries alephdata/aleph-extract-countries:occrp ;
      docker push alephdata/aleph-extract-countries:occrp ;
      docker tag alephdata/aleph:latest alephdata/aleph:occrp ;
      docker push alephdata/aleph:occrp ;
      docker tag alephdata/ui:latest alephdata/ui:occrp ;
      docker push alephdata/ui:occrp ;
    fi
