language: python
cache:
  - apt
  - pip
  - npm
python:
  - "2.7"
services:
  - postgresql
  - rabbitmq
addons:
  postgresql: "9.5"
  apt:
    packages:
      - python-software-properties
      - libtesseract-dev
      - poppler-utils
      - libreoffice
      - djvulibre-bin
      - oracle-java8-installer
      - oracle-java8-set-default
env:
  global:
    - ALEPH_SETTINGS=$TRAVIS_BUILD_DIR/contrib/docker_settings.py
    - ALEPH_DATABASE_NAME=aleph
    - ALEPH_DATABASE_URI=postgresql://localhost/$ALEPH_DATABASE_NAME
    - OAUTH_KEY=fake
    - OAUTH_SECRET=fake
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tesseract-ocr-eng libmagic1
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0.deb && sudo dpkg -i --force-confnew elasticsearch-5.4.0.deb && sudo service elasticsearch start
install:
  - pip install -q --upgrade setuptools pip
  - pip install -r requirements.txt
  - pip install -q -r requirements-testing.txt
  - pip install -e .
before_script:
  - sleep 10
  - psql -c "create database ${ALEPH_DATABASE_NAME}_test;" -U postgres
  - nosetests --version
  - psql --version
script:
  - nosetests --with-coverage --cover-package=aleph
after_success:
  - coveralls
