language: python
cache:
  - apt
  - pip
python:
  - "2.7"
services:
  - postgresql
  - elasticsearch
addons:
  postgresql: "9.4"
  apt:
    packages:
      - python-software-properties
      - libtesseract-dev
env:
  - ALEPH_TEST_SETTINGS=$TRAVIS_BUILD_DIR/test_settings.py
# before_install:
#   - virtualenv ./pyenv --distribute
#   - source ./pyenv/bin/activate
install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install psycopg2 coveralls
  - npm install -g bower
  - bower install
before_script:
  - psql -c 'create database aleph_test;' -U postgres
  - cp $TRAVIS_BUILD_DIR/test_settings.py.tmpl $TRAVIS_BUILD_DIR/test_settings.py
  - nosetests --version
  - psql --version
script:
  - nosetests --with-coverage --cover-package=aleph
after_success:
  - coveralls
