language: python
cache:
  - apt
  - pip
  - npm
python:
  - "2.7"
services:
  - postgresql
  - rabbitmq
addons:
  postgresql: "9.5"
  apt:
    packages:
      - python-software-properties
      - libtesseract-dev
      - wkhtmltopdf
      - poppler-utils
      - libreoffice
      - djvulibre-bin
      - oracle-java8-installer
      - oracle-java8-set-default
env:
  global:
    - ALEPH_SETTINGS=$TRAVIS_BUILD_DIR/contrib/docker_settings.py
    - ALEPH_DATABASE_NAME=aleph
    - ALEPH_DATABASE_URI=postgresql://localhost/$ALEPH_DATABASE_NAME
    - WKHTMLTOPDF_BIN=$TRAVIS_BUILD_DIR/wkhtmltox/bin/wkhtmltopdf
    - OAUTH_KEY=fake
    - OAUTH_SECRET=fake
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tesseract-ocr-eng readpst libmagic1
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.4.0.deb && sudo dpkg -i --force-confnew elasticsearch-5.4.0.deb && sudo service elasticsearch start
  - wget --quiet -O /tmp/wkhtmltox.tar.xv https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - tar -xf /tmp/wkhtmltox.tar.xv -C $TRAVIS_BUILD_DIR
install:
  - pip install --upgrade setuptools pip
  - pip install -r requirements.txt
  - pip install -e .
  - pip install --upgrade git+https://github.com/alephdata/ingestors.git#egg=ingestors
  - pip install coveralls
before_script:
  - sleep 10
  - psql -c "create database ${ALEPH_DATABASE_NAME}_test;" -U postgres
  - nosetests --version
  - psql --version
script:
  - nosetests --with-coverage --cover-package=aleph
after_success:
  - coveralls
