language: python
python:
  - "2.7"
services:
  - postgresql
  - elasticsearch
env:
  - ALEPH_TEST_SETTINGS=test_settings.py
before_install:
  - virtualenv ./pyenv --distribute
  - source ./pyenv/bin/activate
install:
  - sudo apt-get install python-software-properties
  - pip install -r requirements.txt -e .
  - pip install psycopg2 coveralls
before_script:
  - psql -c 'create database aleph_test;' -U postgres
  - sleep 5
  - cp test_settings.py.tmpl test_settings.py
  - nosetests --version
script:
  - nosetests --with-coverage --cover-package=aleph
after_success:
  - coveralls
