sudo: required
services:
  - docker

env:
  global:
    - ALEPH_DATABASE_NAME=aleph
    - ALEPH_DATABASE_URI=postgresql://localhost/$ALEPH_DATABASE_NAME
    - OAUTH_KEY=fake
    - OAUTH_SECRET=fake
    - DOCKER_COMPOSE_VERSION=1.16.1
    - DOCKER_IMAGE_NAME=alephdata/aleph

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo sysctl -w vm.max_map_count=262144
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo echo "ALEPH_DATABASE_NAME=$ALEPH_DATABASE_NAME\nALEPH_DATABASE_URI=$ALEPH_DATABASE_URI\nOAUTH_KEY=$OAUTH_KEY\nOAUTH_SECRET=$OAUTH_SECRET" >> aleph.env
  - docker --version
  - docker-compose --version

install:
  - echo "${TRAVIS_BRANCH}"
  - docker build -t alephdata/aleph:latest .
  - docker build -t alephdata/ui:latest ui
  - docker-compose -f docker-compose.dev.yml build
  - docker-compose -f docker-compose.dev.yml up -d postgres elasticsearch unoservice
  - sleep 4

script:
  - docker-compose -f docker-compose.dev.yml run --rm app /aleph/contrib/devwrapper.sh /aleph/contrib/test.sh

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # push tag as well
  - if [[ $TRAVIS_TAG = $TRAVIS_BRANCH ]]; then
      docker tag alephdata/aleph:latest alephdata/aleph:$TRAVIS_TAG ;
      docker push alephdata/aleph:latest ;
      docker push alephdata/aleph:$TRAVIS_TAG ;
      docker tag alephdata/ui:latest alephdata/ui:$TRAVIS_TAG ;
      docker push alephdata/ui:latest ;
      docker push alephdata/ui:$TRAVIS_TAG ;
    fi
