version: "2"

services:
  postgres:
    image: postgres:10.0
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: aleph
      POSTGRES_PASSWORD: aleph
      POSTGRES_DATABASE: aleph

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-log:/var/log

  rabbitmq:
    image: rabbitmq
    hostname: queue
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  unoservice:
    image: alephdata/unoservice:1.2.1
    restart: on-failure
    tmpfs:
      - /tmp
      - /root/.config
    mem_limit: 1g
    expose:
      - 3000

  app:
    build: .
    command: /bin/bash
    links:
      - postgres
      - elasticsearch
      - rabbitmq
      - unoservice
    # tmpfs: /tmp
    volumes:
      - archive-data:/data
      - polyglot:/polyglot
      - "./:/aleph"
      - "./mappings:/aleph/mappings"
      - "/:/host"
    environment:
      ALEPH_DEBUG: 'true'
      ALEPH_SECRET_KEY: 'development'
      ALEPH_CACHE: 'false'
      ALEPH_OAUTH: 'false'
      ALEPH_EAGER: 'true'
      ALEPH_ARCHIVE_TYPE: 'file'
      ALEPH_ARCHIVE_PATH: '/data'
      POLYGLOT_DATA_PATH: /polyglot
      ALEPH_ELASTICSEARCH_URI: http://elasticsearch:9200/
      ALEPH_DATABASE_URI: postgresql://aleph:aleph@postgres/aleph
      ALEPH_BROKER_URI: amqp://guest:guest@rabbitmq:5672
      UNOSERVICE_URL: http://unoservice:3000/convert
      C_FORCE_ROOT: 'true'
    env_file:
      - aleph.env

  api:
    build: .
    command: python aleph/manage.py runserver -h 0.0.0.0 -p 5000
    expose:
      - 5000
    ports:
      - "5000:5000"
    restart: on-failure
    links:
      - postgres
      - elasticsearch
      - rabbitmq
      - unoservice
    volumes:
      - archive-data:/data
      - polyglot:/polyglot
      - "./aleph:/aleph/aleph"
      - "/:/host"
    environment:
      ALEPH_DEBUG: 'true'
      ALEPH_SECRET_KEY: 'development'
      ALEPH_CACHE: 'false'
      ALEPH_EAGER: 'true'
      ALEPH_ARCHIVE_TYPE: 'file'
      ALEPH_ARCHIVE_PATH: '/data'
      POLYGLOT_DATA_PATH: /polyglot
      ALEPH_ELASTICSEARCH_URI: http://elasticsearch:9200/
      ALEPH_DATABASE_URI: postgresql://aleph:aleph@postgres/aleph
      ALEPH_BROKER_URI: amqp://guest:guest@rabbitmq:5672
      UNOSERVICE_URL: http://unoservice:3000/convert
      C_FORCE_ROOT: 'true'
    env_file:
      - aleph.env
  
  ui:
    build: ui
    links:
      - api
    command: npm run start
    ports:
      - "8080:3000"
    volumes:
      - "./ui/src:/alephui/src"
      - "./ui/public:/alephui/public"
      - "./ui/.tx:/alephui/.tx"
      - "./ui/package.json:/alephui/package.json"
    environment:
      REACT_APP_API_ENDPOINT: '/api/2'
    env_file:
      - aleph.env

volumes:
  archive-data: {}
  polyglot: {}
  elasticsearch-data: {}
  elasticsearch-log: {}
  postgres-data: {}
  rabbitmq-data: {}