version: "3.2"

services:
  postgres:
    image: postgres:10.0
    hostname: postgres
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: aleph
      POSTGRES_PASSWORD: aleph
      POSTGRES_DATABASE: aleph

  elasticsearch:
    build:
      context: services/elasticsearch
      cache_from:
        - alephdata/aleph-elasticsearch:latest
    image: alephdata/aleph-elasticsearch:latest
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "19200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  redis:
      image: redis:alpine
      command: ["redis-server", "--appendonly", "yes"]
      volumes:
        - redis-data:/data

  convert-document:
    build:
      context: services/convert-document
      cache_from:
        - alephdata/convert-document:latest
    image: alephdata/convert-document:latest
    restart: on-failure
    tmpfs:
      - /tmp
      - /root/.config
    expose:
      - 3000

  recognize-text:
    build:
      context: services/recognize-text
      cache_from:
        - alephdata/recognize-text:latest
    image: alephdata/recognize-text:latest
    restart: on-failure
    expose:
      - 50000

  ingest-file:
    build:
      context: services/ingest-file
      cache_from:
        - alephdata/ingest-file:latest
    image: alephdata/ingest-file:latest
    hostname: ingest
    tmpfs: /tmp
    volumes:
      - archive-data:/data
      - "./services/ingest-file/ingestors:/ingestors/ingestors"
      - "./services/ingest-file/tests:/ingestors/tests"
    environment:
      ARCHIVE_TYPE: 'file'
      REDIS_URL: 'redis://redis:6379/0'
      BALKHASH_BACKEND: 'postgresql'
      BALKHASH_DATABASE_URI: 'postgresql://aleph:aleph@postgres/aleph'
      OCR_SERVICE: 'recognize-text:50000'
      UNOSERVICE_URL: 'http://convert-document:3000/convert'
    links:
      - postgres
      - redis
      - convert-document
      - recognize-text
    restart: on-failure
    env_file:
      - aleph.env

  app:
    build:
      context: .
      cache_from:
        - alephdata/aleph:latest
    image: alephdata/aleph:latest
    hostname: aleph
    command: /bin/bash
    links:
      - postgres
      - elasticsearch
      - redis
      - ingest-file
    tmpfs: /tmp
    volumes:
      - archive-data:/data
      - "./aleph:/aleph/aleph"
      - "./contrib:/aleph/contrib"
      - "./mappings:/aleph/mappings"
      - "/:/host"
    cap_add:
      - SYS_PTRACE
    environment:
      ALEPH_DEBUG: 'true'
      ALEPH_SECRET_KEY: 'development'
      ALEPH_OAUTH: 'false'
      ARCHIVE_TYPE: 'file'
      BALKHASH_BACKEND: 'postgresql'
      BALKHASH_DATABASE_URI: 'postgresql://aleph:aleph@postgres/aleph'
      ALEPH_DATABASE_URI: 'postgresql://aleph:aleph@postgres/aleph'
    env_file:
      - aleph.env

  api:
    build:
      context: .
      cache_from:
        - alephdata/aleph:latest
    image: alephdata/aleph:latest
    command: aleph runserver -h 0.0.0.0 -p 5000 --threaded
    expose:
      - 5000
    ports:
      - "5000:5000"
    restart: on-failure
    links:
      - postgres
      - elasticsearch
      - redis
      - ingest-file
    tmpfs: /tmp
    volumes:
      - archive-data:/data
      - "./aleph:/aleph/aleph"
      - "/:/host"
    environment:
      ALEPH_DEBUG: 'true'
      ALEPH_SECRET_KEY: 'development'
      ARCHIVE_TYPE: 'file'
      BALKHASH_BACKEND: 'postgresql'
      BALKHASH_DATABASE_URI: 'postgresql://aleph:aleph@postgres/aleph'
    env_file:
      - aleph.env
  
  ui:
    build:
      context: ui
      cache_from:
        - alephdata/aleph-ui:latest
    image: alephdata/aleph-ui
    links:
      - api
    command: npm run start
    ports:
      - "8080:3000"
    volumes:
      - "./ui/src:/alephui/src"
      - "./ui/public:/alephui/public"
      - "./ui/.tx:/alephui/.tx"
      - "./ui/package.json:/alephui/package.json"
    environment:
      REACT_APP_API_ENDPOINT: '/api/2'
    env_file:
      - aleph.env

volumes:
  archive-data: {}
  elasticsearch-data: {}
  postgres-data: {}
  rabbitmq-data: {}
  redis-data: {}