# Upgrade job for making sure that Aleph DB is up2date
apiVersion: batch/v1
kind: Job
metadata:
  name: search-upgrade
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: secrets-mounted
          secret:
            secretName: secrets-mounted
      containers:
        - name: search-upgrade
          image: alephdata/aleph:2.1.5
          imagePullPolicy: Always
          command: ["aleph", "upgrade"]
          resources:
            requests:
              memory: 500Mi
          envFrom:
            - configMapRef:
                name: search-config
            - secretRef:
                name: common-secrets
          volumeMounts:
            - mountPath: /secrets
              name: secrets-mounted
        - name: search-db-sidecar
          image: b.gcr.io/cloudsql-docker/gce-proxy:latest
          imagePullPolicy: Always
          command:
            - /cloud_sql_proxy
            - -dir=/cloudsql
            - -instances=REPLACEME:SQL_CONNECTION_STRING
            - -credential_file=/secrets/service-account.json
          livenessProbe:
            exec:
              command:
                - nc
                - -z
                - 127.0.0.1
                - "5432"
          readinessProbe:
            exec:
              command:
                - nc
                - -z
                - 127.0.0.1
                - "5432"
          volumeMounts:
            - mountPath: /secrets
              name: secrets-mounted
