global:
  dbInstance: clustername:region:core-postgres=tcp:5432
  imagetag: latest


api:
  minReplicas: 1
  maxReplicas: 2
  resources:
    requests:
      memory: 500Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 600m


config:
  ALEPH_URL_SCHEME: https
  ALEPH_APP_TITLE: 'OCCRP Data (Staging)'
  ALEPH_OCR_VISION_API: 'false'
  ALEPH_CORS_ORIGINS: '*'
  ALEPH_ARCHIVE_TYPE: gs
  ALEPH_ARCHIVE_BUCKET: 'bucket-name'
  ALEPH_PASSWORD_LOGIN: 'true'
  ALEPH_ADMINS: 'admin@example.com'
  ALEPH_MAIL_FROM: notifications@example.com
  ALEPH_MAIL_HOST: core-mail.default.svc.cluster.local
  ALEPH_MAIL_USERNAME: ''
  ALEPH_MAIL_PASSWORD: ''
  ALEPH_MAIL_PORT: '25'
  ALEPH_MAIL_TLS: 'false'
  ALEPH_MAIL_SSL: 'false'
  ALEPH_UI_URL: https://staging.data.occrp.org
  ALEPH_FAVICON: https://cdn.occrp.org/common/logo/RedTransparent_globe.png
  ALEPH_LOGO: https://cdn.occrp.org/common/logo/RedTransparent_globe.png
  ALEPH_ELASTICSEARCH_SHARDS: '5'
  ALEPH_OAUTH: 'false'
  ALEPH_OAUTH_KEY: key-name
  ALEPH_OAUTH_NAME: provider-name
  ALEPH_OAUTH_SCOPE: read
  ALEPH_OAUTH_BASE_URL: ''
  ALEPH_OAUTH_TOKEN_URL: ''
  ALEPH_OAUTH_AUTHORIZE_URL: ''


convert-document:
  minReplicas: 2
  maxReplicas: 5
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 600Mi
      cpu: 1000m


extract-entities:
  minReplicas: 2
  maxReplicas: 5
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 1500Mi
      cpu: 1000m


index-admin:
  image: lmenezes/cerebro
  replicas: 1
  maxSurge: 1
  maxUnavailable: 100%
  resources:
    limits:
      memory: 2Gi


index:
  replicas: 4
  resources:
    requests:
      memory: 2Gi
      cpu: 300m
      storage: 100Gi
    limits:
      memory: 3Gi
      cpu: 1000m
  minMasterNodes: "2"
  ES_JAVA_OPTS_MEMORY_LIMIT: -Xms2g -Xmx3g


queue:
  image: rabbitmq:management-alpine
  replicas: 1
  resources:
    requests:
      memory: 1Gi
      cpu: 200m
      storage: 10Gi
    limits:
      memory: 1.5Gi
      cpu: 400m


recognize-text:
  minReplicas: 2
  maxReplicas: 5
  resources:
    requests:
      memory: 800Mi
      cpu: 1000m
    limits:
      memory: 1400Mi
      cpu: 1500m


scheduler:
  resources:
    requests:
      memory: 200Mi
      cpu: 200m
    limits:
      memory: 500Mi
      cpu: 500m


web:
  replicas: 2
  maxSurge: 2
  resources:
    requests:
      memory: 200Mi
      cpu: 200m
    limits:
      memory: 300Mi
      cpu: 500m


worker:
  minReplicas: 2
  maxReplicas: 10
  resources:
    requests:
      memory: 500Mi
      cpu: 300m
    limits:
      memory: 4Gi
      cpu: 1000m
