name: Package and Upload Helm Chart Release

on: [push]

jobs:
  build:
    name: Package and Upload Helm Chart Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(cat contrib/helm/charts/aleph/Chart.yaml | grep version | awk '{print $2}')

      # Build for every commit
      - name: Package chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: |
            helm package contrib/helm/charts/aleph --version ${{ steps.get_version.outputs.VERSION }}+${{ github.sha }} --destination charts/
            helm repo index charts/
      - name: Upload index to GCS
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: charts/index.yaml
          destination: aleph-helm-charts
      - name: Upload chart to GCS
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: charts/aleph-${{ steps.get_version.outputs.VERSION }}+${{ github.sha }}.tgz
          destination: aleph-helm-charts

      # Build for tags
      - name: Package chart
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: |
            helm package contrib/helm/charts/aleph --version ${{ steps.get_version.outputs.VERSION }} --destination charts/
            helm repo index charts/
      - name: Upload index to GCS
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: charts/index.yaml
          destination: aleph-helm-charts
      - name: Upload chart to GCS
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: charts/aleph-${{ steps.get_version.outputs.VERSION }}.tgz
          destination: aleph-helm-charts
